---
title: "tidy-data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(tibble)
library(skimr)
library(magrittr)
library(purrr)
library(ggtext)
library(grid)
library(ggrepel)
library(directlabels)
#devtools::install_github('thomasp85/ggfx')
library(ggfx)
```

## Including Plots

You can also embed plots, for example:

```{r load_data, echo=FALSE}
# loading resq dataset
resq_data <- read_excel("resq-raw-data/sample_hospital.xlsx")

# checking what rows that include NA values
resq_data %>%
  summarise_all(funs(sum(is.na(.)))) %>%
  pivot_longer(everything()) %>%
  filter(value > 0)

# replacing NA's with zero's
resq_data %<>%
  replace(is.na(.), 99)

# just checking if nihss_score actually is numeric - stated as a text in resq data legend tab in excel
class(resq_data$nihss_score)

# creating tribbles for each variable/legend
trib_department_type <- tribble(
  ~department_type, ~DeptTypeStr,
  1, "neurology",
  2, "neurosurgery",
  3, "anesthesiology/resusccitation/critical care department",
  4, "internal medicine",
  5, "geriatrics",
  6, "other",
  99, "Unknown",
)

trib_hosp_in <- tribble(
  ~hospitalized_in, ~HospInStr,
  1, "Stroke unit/ICU",
  2, "Other monitored bed (telemetry)",
  3, "Standard bed",
  99, "Not applicable",
)

trib_stroke_type <- tribble(
  ~stroke_type, ~StrokeTypeStr,
  1, "Ischemic Stroke",
  2, "Intracerebral hemorrhage",
  3, "Transient ischemic attack - TIA",
  4, "Subarachnoid hemorrhage",
  5, "Cerebral venous thrombosis",
  6, "Undetermined",
  99, "Not applicable",
)

trib_NIHSS <- tribble(
  ~nihss, ~NIHSSStr,
  1, "Not performed",
  2, "Performed",
  3, "Not known",
  99, "Unknown",
)

trib_CT_MRI <- tribble(
  ~ct_mri, ~CTMRIStr,
  1, "Not performed",
  2, "Performed",
  3, "Not known",
  99, "Not applicable",
)

trib_CT_Time <- tribble(
  ~ct_time, ~ctTimeStr,
  1, "Within 1 hour after admission",
  2, "Later than 1 hour after admission",
  99, "Not applicable",
)

trib_recanalization_procedures <- tribble(
  ~recanalization_procedures, ~RecanProcStr,
  1, "Not done - primary centre / comprehensive centre",
  2, "IV tPa - primary centre / comprehensive centre",
  3, "IV tPa + endovascular treatment - comprehensive centre",
  4, "Endovascular treatment alone - comprehensive centre",
  5, "IV tPa + referred to another centre for endovascular treatment - primary centre",
  6, "Referred to another centre for endovascular treatment - primary centre",
  7, "Patient referred to another centre for endovascular treatment and hospitalization continues at the referred to centre - comprehensive centre",
  8, "Patient referred for endovascular treatment and patient is returned to the initial centre - comprehensive centre",
  9, "Patient was returned to the initial centre after recanalization procedures were performed at another centre",
  99, "Not applicable",
)

trib_dysphagia_screening <- tribble(
  ~dysphagia_screening, ~DysphagiaStr,
  1, "Yes/Guss test",
  2, "Yes/other test",
  3, "Was performed at another center",
  4, "No",
  5, "Patient could not be tested (intubated)",
  6, "Not known",
  99, "Not applicable",
)

trib_afib_flutter <- tribble(
  ~afib_flutter, ~AfibFlutterStr,
  1, "Known aFib",
  2, "Newly-detected at admission",
  3, "Detected during hospilization",
  4, "Not detected",
  5, "Not known",
  99, "Not applicable",
)

trib_antithrombotics <- tribble(
  ~antithrombotics, ~AntithromboticsStr,
  1, "antiplatelets",
  2, "Vitamin K antagonist",
  3, "dabigratan",
  4, "rivaroxaban",
  5, "apixaban",
  6, "edoxaban",
  7, "LMWH or heparin in prophylactic dose",
  8, "LMWH or heparin in full anticoagulant dose",
  9, "Not prescriped\but recommended",
  10, "Nothing",
  99, "Not applicable",
)

trib_statin <- tribble(
  ~statin, ~StatinStr,
  1, "Yes",
  2, "No",
  3, "Not known",
  99, "Not applicable",
)

trib_smoking_cessation <- tribble(
  ~smoking_cessation, ~SmokingCessationStr,
  1, "Yes",
  2, "No",
  3, "Not a smoker",
  99, "Unknown",
)

trib_antihypertensive <- tribble(
  ~antihypertensive, ~AntihypertensiveStr,
  1, "Yes",
  2, "No",
  3, "Not known",
  99, "Not applicable",
)

trib_discharge_dest <- tribble(
  ~discharge_destination, ~DistDestStr,
  1, "Home",
  2, "Transferred within the same centre",
  3, "Transferred to another centre",
  4, "Social care facility",
  5, "Dead",
  99, "Not applicable",
)

trib_discharge_mrs <- tribble(
  ~discharge_mrs, ~DistMRSStr,
  1, "unknown/calculate",
  2, "0",
  3, "1",
  4, "2",
  5, "3",
  6, "4",
  7, "5",
  8, "6",
  99, "Not Applicable",
)

# getting a summary of the resq data
skim(resq_data)
summary(resq_data$department_type)

# you don't need to add trib_department_type to the left_join...
resq_merge <- resq_data %>%
  left_join(trib_department_type, by = "department_type") %>%
  left_join(trib_hosp_in, by = "hospitalized_in") %>%
  left_join(trib_stroke_type, by = "stroke_type") %>%
  left_join(trib_NIHSS, by = "nihss") %>%
  left_join(trib_CT_MRI, by = "ct_mri") %>%
  left_join(trib_CT_Time, by = "ct_time") %>%
  left_join(trib_recanalization_procedures, by = "recanalization_procedures") %>%
  left_join(trib_dysphagia_screening, by = "dysphagia_screening") %>%
  left_join(trib_afib_flutter, by = "afib_flutter") %>%
  left_join(trib_antithrombotics, by = "antithrombotics") %>%
  left_join(trib_statin, by = "statin") %>%
  left_join(trib_smoking_cessation, by = "smoking_cessation") %>%
  left_join(trib_antihypertensive, by = "antihypertensive") %>%
  left_join(trib_discharge_mrs, by = "discharge_mrs") %>%
  left_join(trib_discharge_dest, by = "discharge_destination")
```


30 Day Mortality Rate. Being assigned a value of 1 = dead, 0 = alive.
```{r mortal ity, echo=FALSE}
resq_mort <- resq_merge %>%
  mutate(
    within30DayMort = if_else((hospital_days <= 30 & DistDestStr == "Dead"), 1, 0),
  )

resq_mort %<>%
  dplyr::group_by(discharge_date) %>%
  mutate(
    Mortality30dMean_m = mean(within30DayMort) * 100,
    DTNMean_m = mean(replace(door_to_needle, door_to_needle == 99, NA), na.rm = TRUE),
    DTNMedian_m = median(replace(door_to_needle, door_to_needle == 99, NA), na.rm = TRUE),
    DTGMean_m = mean(replace(door_to_groin, door_to_groin == 99, NA), na.rm = TRUE),
    DTGMedian_m = median(replace(door_to_groin, door_to_groin == 99, NA), na.rm = TRUE),
    DISMRSMean_m = mean(replace(discharge_mrs, discharge_mrs == 99 & 1, NA), na.rm = TRUE),
    DISMRSMedian_m = median(replace(discharge_mrs, discharge_mrs == 99 & 1, NA), na.rm = TRUE),
    NIHSSScoreMean_m = mean(replace(nihss_score, nihss_score == 99, NA), na.rm = TRUE),
    NIHSSScoreMedian_m = median(replace(nihss_score, nihss_score == 99, NA), na.rm = TRUE)
  )


df <- resq_mort %>%
  dplyr::group_by(discharge_date) %>%
  summarise(
    Mortality30dMean = mean(within30DayMort) * 100,
    DTNMean = mean(replace(door_to_needle, door_to_needle == 99, NA), na.rm = TRUE),
    DTNMedian = median(replace(door_to_needle, door_to_needle == 99, NA), na.rm = TRUE),
    DTGMean = mean(replace(door_to_groin, door_to_groin == 99, NA), na.rm = TRUE),
    DTGMedian = median(replace(door_to_groin, door_to_groin == 99, NA), na.rm = TRUE),
    DISMRSMean = mean(replace(discharge_mrs, discharge_mrs == 99 & 1, NA), na.rm = TRUE),
    DISMRSMedian = median(replace(discharge_mrs, discharge_mrs == 99 & 1, NA), na.rm = TRUE),
    NIHSSScoreMean = mean(replace(nihss_score, nihss_score == 99, NA), na.rm = TRUE),
    NIHSSScoreMedian = median(replace(nihss_score, nihss_score == 99, NA), na.rm = TRUE)
  )


# THERE IS NO DTN/DTG DATA IN 2020, IT IS EMPTY IN RAW DATA AS WELL

########## TREND LINES ##########

testText <- grobTree(textGrob("Annotation testing", x = 0.10, y = 0.40, hjust = 0, gp = gpar(col = "black", fontsize = 13, fontface = "italic")))

p_trend_mort <- ggplot(
  df[df$discharge_date < 2201, ],
  aes(x = discharge_date, y = Mortality30dMean)
) +
  geom_line(color = "#0F85C8", alpha = .7, size = 1.7) +
  geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 4, stroke = 1.7) +
  theme_classic() +
  ylab("Mortality rate %") +
  xlab("Discharge date") +
  expand_limits(y = 0) +
  labs(
    title = "<span style = 'color: #0F85C8;'> Mortality rate %</span> evolution"
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.03, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.77, vjust = 0.77),
    plot.caption = element_text(hjust = 0, size = 6),
  ) +
  annotation_custom(testText) +
  geom_text(aes(label = round(Mortality30dMean, digits = 2)), color = "#0F85C8", nudge_y = 0.8) +

p_trend_mort

p_mort_vs_DTN <- ggplot(
  df,
  aes(y = Mortality30dMean, x = DTNMean)
) +
  geom_line(color = "#0F85C8", alpha = .7, size = 1.7) +
  geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 4, stroke = 1.7) +
  theme_classic() +
  ylab("Mortality rate %") +
  xlab("Door to needle") +
  expand_limits(y = 0, x = 0) +
  labs(
    title = "<span style = 'color: #0F85C8;'>Mortality rate %</span> against door to needle evolution"
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.04, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.77, vjust = 0.77),
    plot.caption = element_text(hjust = 0, size = 6),
  ) +
  annotation_custom(testText) +
  geom_text(aes(label = ifelse((round(Mortality30dMean, digits = 2) == 10), "",
    ifelse(round(Mortality30dMean, digits = 2) == 10.7,
      "", round(Mortality30dMean, digits = 2)
    )
  )),
  color = "#0F85C8", nudge_y = 0.9, nudge_x = 0.1)

p_mort_vs_DTN

p_mort_vs_DTG <- ggplot(
  df,
  aes(y = Mortality30dMean, x = DTGMean)
) +
  geom_line(color = "#0F85C8", alpha = .7, size = 1.7) +
  geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 4, stroke = 1.7) +
  theme_classic() +
  ylab("Mortality rate %") +
  xlab("Door to groin") +
  expand_limits(y = 0, x = 0) +
  labs(
    title = "<span style = 'color: #0F85C8;'>Mortality rate %</span> against door to groin evolution"
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.05, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.77, vjust = 0.77),
    plot.caption = element_text(hjust = 0, size = 6),
  ) +
  annotation_custom(testText) + 
    geom_text(aes(label = ifelse((round(Mortality30dMean, digits = 2) == 10), "",
    ifelse(round(Mortality30dMean, digits = 2) == 10.7,
      "", round(Mortality30dMean, digits = 2)
    )
  )),
  color = "#0F85C8", nudge_x = 3)

p_mort_vs_DTG

# Discharge mRS only have 2 entries for each DTG and DTN, which means we only have two data points in the plots.

p_trend_mRS <- ggplot(
  df[df$discharge_date < 2201 & df$discharge_date >= 2017, ],
  aes(x = discharge_date, y = DISMRSMean)
) +
  geom_line(color = "#0F85C8", alpha = .7, size = 1.7) +
  geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 4, stroke = 1.7) +
  theme_classic() +
  ylab("Discharge mRS") +
  xlab("Discharge date") +
  expand_limits(y = 0) +
  labs(
    title = "<span style = 'color: #0F85C8;'> Discharge mRS</span> evolution"
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.03, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.95, vjust = 1),
    plot.caption = element_text(hjust = 0, size = 6),
  ) +
  annotation_custom(testText) +
  geom_text(aes(label = round(DISMRSMean, digits = 2)), color = "#0F85C8", nudge_y = 0.3)

p_trend_mRS

p_mRS_vs_DTN <- ggplot(
  df,
  aes(y = DISMRSMean, x = DTNMean)
) +
  geom_line(color = "#0F85C8", alpha = .7, size = 1.7) +
  geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 4, stroke = 1.7) +
  theme_classic() +
  ylab("Discharge mRS") +
  xlab("Door to needle") +
  expand_limits(y = 0, x = 0) +
  labs(
    title = "<span style = 'color: #0F85C8;'>Discharge mRS</span> against door to needle evolution"
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.03, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.95, vjust = 0.77),
    plot.caption = element_text(hjust = 0, size = 6),
  ) +
  annotation_custom(testText) +
  geom_text_repel(aes(label = round(DISMRSMean, digits = 2)), color = "#0F85C8", nudge_x = 0.3)

p_mRS_vs_DTN

p_mRS_vs_DTG <- ggplot(
  df,
  aes(y = DISMRSMean, x = DTGMean)
) +
  geom_line(color = "#0F85C8", alpha = .7, size = 1.7) +
  geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 4, stroke = 1.7) +
  theme_classic() +
  ylab("Discharge mRS") +
  xlab("Door to groin") +
  expand_limits(y = 0, x = 0) +
  geom_text_repel(aes(label = round(DISMRSMean, digits = 2)), hjust = 0, color = "#0F85C8") +
  labs(
    title = "<span style = 'color: #0F85C8;'>Discharge mRS</span> against door to groin evolution"
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.025, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.95, vjust = 0.77),
    plot.caption = element_text(hjust = 0, size = 6),
  ) +
  annotation_custom(testText)

p_mRS_vs_DTG

p_mRS_vs_nihss <- ggplot(
  df,
  aes(y = DISMRSMean, x = NIHSSScoreMean)
) +
  geom_line(color = "#0F85C8", alpha = .7, size = 1.7) +
  geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 4, stroke = 1.7) +
  theme_classic() +
  ylab("Discharge mRS") +
  xlab("NIHSS score") +
  expand_limits(y = 0) +
  xlim(21, 23) +
  geom_text(aes(label = round(DISMRSMean, digits = 2)), hjust = 0, color = "#0F85C8", nudge_y = 0.3) +
  labs(
    title = "<span style = 'color: #0F85C8;'>Discharge mRS</span> against NIHSS score evolution"
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.025, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.95, vjust = 0.77),
    plot.caption = element_text(hjust = 0, size = 6),
  ) +
  annotation_custom(testText)

p_mRS_vs_nihss

p_trend_nihss <- ggplot(
  df[df$discharge_date < 2201, ],
  aes(x = discharge_date, y = NIHSSScoreMean)
) +
  geom_line(color = "#0F85C8", alpha = .7, size = 1.7) +
  geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 4, stroke = 1.7) +
  theme_classic() +
  ylab("NIHSS score") +
  xlab("Discharge date") +
  expand_limits(y = 0) +
  labs(
    title = "<span style = 'color: #0F85C8;'>NIHSS score</span> evolution"
  ) +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.03, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.65, vjust = 1),
    plot.caption = element_text(hjust = 0, size = 6),
  ) +
  annotation_custom(testText) +
  geom_text(aes(label = round(NIHSSScoreMean, digits = 2)), color = "#0F85C8", nudge_y = 1.6)

p_trend_nihss

# p_nihss_vs_DTN <- ggplot(df,
# aes(y = DISMRSMean, x = NIHSSScoreMean)) +
#   geom_line(color="#0F85C8", alpha=.7, size=1.7) +
#   geom_point(shape = 21, color = "#0F85C8", fill = "white", size = 5, stroke = 1.7) +
#   theme_classic() +
#   ylab("NIHSS score") +
#   xlab("Door to needle") +
#   expand_limits(y=0) +
#   xlim(21, 23) +
#     labs(
#     title = "<span style = 'color: #0F85C8;'>NIHSS score</span> against door to needle evolution"
#   ) +
#   theme(
#     plot.title = element_markdown(),
#     axis.title.x = element_text(hjust=0.03, vjust=0.2),
#     axis.title.y = element_text(hjust=0.95, vjust=0.77),
#     plot.caption = element_text(hjust=0, size=6),
#     ) +
#   annotation_custom(testText) + geom_text_repel(aes(label=round(NIHSSScoreMean, digits=2)), color = "#0F85C8" )
#
# p_nihss_vs_DTN

p_violin_DTN <- ggplot(
  resq_mort[resq_mort$door_to_needle < 99 & resq_mort$discharge_date < 2201, ],
  aes(x = discharge_date, y = DTNMean_m, color = "Mean")
) +
  geom_violin(aes(x = discharge_date, y = door_to_needle, color = as.factor(discharge_date)), alpha = .4) +
  geom_line() +
  geom_line(aes(y = DTNMedian_m, color = "Median")) +
  theme_classic() +
  ylab("Door to needle") +
  xlab("Discharge date") +
  expand_limits(y = 0) +
  ggtitle("Door to needle evolution") +
  theme(
    axis.title.x = element_text(hjust = 0.15, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.84, vjust = 0.8),
    plot.caption = element_text(hjust = 0, size = 6),
  )

p_violin_DTN

p_violin_DTG <- ggplot(
  resq_mort[resq_mort$door_to_groin < 99 & resq_mort$discharge_date < 2201, ],
  aes(x = discharge_date, y = DTGMean_m, color = "Mean")
) +
  geom_violin(aes(x = discharge_date, y = door_to_groin, color = as.factor(discharge_date)), alpha = .4) +
  geom_line() +
  geom_line(aes(y = DTGMedian_m, color = "Median")) +
  theme_bw() +
  ylab("Door to groin") +
  xlab("Discharge date") +
  expand_limits(y = 0) +
  ggtitle("Door to groin evolution") +
  theme(
    axis.title.x = element_text(hjust = 0.15, vjust = 0.2),
    axis.title.y = element_text(hjust = 0.75, vjust = 0.8),
    plot.caption = element_text(hjust = 0, size = 6),
  )
  

p_violin_DTG

p_violin_dismrs <- ggplot(
  resq_mort[resq_mort$discharge_mrs < 99 & resq_mort$discharge_date < 2201, ],
  aes(x = discharge_date, y = DISMRSMean_m, color = "Mean")
) +
  geom_violin(aes(x = discharge_date, y = discharge_mrs, color = as.factor(discharge_date)), alpha = .4) +
  geom_line() +
  geom_line(aes(y = DISMRSMedian_m, color = "Median")) +
  theme_bw() +
  ylab("Discharge mrs") +
  xlab("Discharge date") +
  expand_limits(y = 0)

p_violin_dismrs

# FUNNEL PLOT MORTALITY AGAINST PATIENTS, MADE UP DATA KIND OF
dt <- data.frame(
  patients = c(42, 71, 255, 489, 753), # these values are also made up, except for the last one, which is the res-q patient count
  mortalityExpected = c(11.8, 7.14, 10, 10.7, 8.5),
  mortalityObserved = c(17, 12, 9.5, 10.2, 9), # this value is made up, as we don't have multiple departments
  unit = factor(c("A", "B", "C", "D", "E"))
)

dt$SR <- dt$mortalityObserved / dt$mortalityExpected


# Scatter plot in ggplot
a <- ggplot(dt, aes(x = patients, y = SR)) +
  geom_point()

a <- a + geom_hline(aes(yintercept = 1), color = "#0F85C8")

a

# Add a 95% Poisson limit, by using the density function to get the quantile value for each 'expected'.
lkup <- data.frame(id = seq(1, max(dt$patients), 1))
lkup$upper <- (qpois(0.975, lambda = lkup$id) - 0.025) / lkup$id
lkup$lower <- (qpois(0.025, lambda = lkup$id) - 0.975) / lkup$id

lkup <- gather(lkup, key, value, -id)

a + geom_line(aes(x = id, y = value, col = key), data = lkup) +
  annotation_custom(testText) +
  theme_classic() +
  labs(
    title = "<span style = 'color: #0F85C8;'>Standardised mortality rate</span> against patients"
  ) +
  ylab("Standardised ratio") +
  xlab("Patients") +
  theme(
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.04, vjust = 0),
    axis.title.y = element_text(hjust = 0.96, vjust = 0.96),
    plot.caption = element_text(hjust = 0, size = 6),
  )


survivalAfterText <- grobTree(textGrob("60%", x = 0.82, y = 0.60, hjust = 0, gp = gpar(col = "#F8766D", fontsize = 13)))
survivalBeforeText <- grobTree(textGrob("50%", x = 0.82, y = 0.50, hjust = 0, gp = gpar(col = "#0F85C8", fontsize = 13)))


dfCancerRegistry <- data.frame(
  survivalPercentBefore = c(94.8, 69, 50),
  survivalPercentAfter = c(96.4, 77, 60),
  time = c("30 days", "1 year", "2 years")
)

dfCancerPlot <- ggplot(dfCancerRegistry, aes(x = time, y = survivalPercentBefore, group = 1)) + theme_classic()
  

dfCancerPlot + 
  geom_line(aes(color="#F8766D")) + 
  geom_line(aes(x = time, y = survivalPercentAfter, group = 1, color="#0F85C8")) + 
  ylim(0, 100) +
  xlim("30 days", "1 year", "2 years") +
  xlab("Time passed after discharge") +
  ylab("Survival rate %") +
  ggtitle(label = "Difference in survival rate <span style = 'color:#0F85C8;'>before</span> and <span
                  style = 'color: #F8766D;'>after</span> adding cancer registry in DK"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_markdown(),
    axis.title.x = element_text(hjust = 0.215, vjust = 0),
    axis.title.y = element_text(hjust = 0.96, vjust = 0.96),
  ) +
  annotation_custom(survivalBeforeText) +
  annotation_custom(survivalAfterText)

########## MAYBE USEFUL IDK? ##########
# p_dtn <- ggplot(resq_mort[resq_mort$door_to_needle<99 & resq_mort$discharge_date<2201 & resq_mort$discharge_date>2017,], aes(x = door_to_needle, y = Mortality30dMean, color=as.factor(discharge_date))) +
#   geom_boxplot() +
#   geom_jitter(alpha=.4) +
#   geom_point(aes(x=DTNMean), size = 4) +
#   theme_bw()
#
# p_dtn
#
# p_dtg <- ggplot(resq_mort[resq_mort$door_to_groin<99 & resq_mort$discharge_date<2201,], aes(x = Mortality30dMean, y = door_to_groin, color=as.factor(discharge_date))) +
#   geom_boxplot() +
#   geom_jitter() +
#   theme_bw()
#
# p_dtg
#
# #NIHSS score is not really a KPI though
# p_nihss_score_jitter <- ggplot(resq_mort[resq_mort$nihss_score<99 & resq_mort$discharge_date<2201,], aes(x = Mortality30dMean, y = nihss_score, color=as.factor(discharge_date))) +
#   geom_violin() +
#   geom_jitter() +
#   theme_bw()
#
# p_nihss_score_jitter
#
# p_nihss_score <- ggplot(resq_mort[resq_mort$nihss_score<99 & resq_mort$discharge_date<2201,], aes(x = Mortality30dMean, y = nihss_score, color=as.factor(discharge_date))) +
#   geom_violin() +
#   theme_bw()
#
# p_nihss_score
#
# #this might have way too many dots to show. decreases readability
# p_dis_mrs_jitter <- ggplot(resq_mort[resq_mort$discharge_mrs>1 & resq_mort$discharge_mrs<99 & resq_mort$discharge_date<2201,], aes(x = Mortality30dMean, y = discharge_mrs, color=as.factor(discharge_date))) +
#   geom_violin() +
#   geom_jitter() +
#   theme_bw()
#
# p_dis_mrs_jitter
#
# p_dis_mrs <- ggplot(resq_mort[resq_mort$discharge_mrs>1 & resq_mort$discharge_mrs<99 & resq_mort$discharge_date<2201,], aes(x = Mortality30dMean, y = discharge_mrs, color=as.factor(discharge_date))) +
#   geom_violin() +
#   theme_bw()
#
# p_dis_mrs


```


